language: node_js
sudo: false
node_js:
  - 5.6
install:
- npm install purescript@0.9.1 bower pulp@9.0.1 purescript-psa -g
- bower install
script:
  - pulp build --censor-lib && pulp docs
  - bower link
  - cd example/ && bower -q link purescript-websocket-simple && bower -q install && pulp build --censor-lib

after_success:
  - >-
    test $TRAVIS_TAG &&
    psc-publish > .pursuit.json &&
    curl -X POST https://pursuit.purescript.org/packages \
      -d @.pursuit.json \
      -H 'Accept: application/json' \
      -H "Authorization: token ${GITHUB_TOKEN}"
